version: 2
updates:
  - package-ecosystem: docker
    directories: [/, /apps/api/test/ssh-target]
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
