http:
  routers:
    certshell:
      rule: Host(`{{ env "SSH_DOMAIN" }}`)
      service: certshell
    pocket-id:
      rule: Host(`{{ env "ID_DOMAIN" }}`)
      service: pocket-id
  services:
    certshell:
      loadBalancer:
        servers: [{ url: "http://certshell:3000" }]
    pocket-id:
      loadBalancer:
        servers: [{ url: "http://pocket-id:1411" }]
